### ISSUE TITLE
Faulty Projections

### ISSUE THREAD

**Issue by jeremysze** [ywnch/toolbox#1]
I am trying to use your connect_poi() function to connect some geocoded locations into the street network. However, I am getting all my locations removed as faulty projections. I was looking at your code, however my python skills are not sophisticated enough to understand your code and why my coordinates are faulty in order to fix it.

**Comment by jeremysze** [comment]
After more digging, I found out the issue lies with the default threshold. I am working with EPSG 2263, which is in feet. The threshold of 200 is too restrictive. In any case, this piece of code is great! I was trying to create something similar and was stumbling with splitting edges, when I came upon your work!

**Comment by ywnch** [comment]
Thanks for noting down the details of the issue and glad that it worked for you! I guess I will make the setting and transformation of EPSG more explicit to avoid the issue. :)
