### ISSUE TITLE
duplication in node coordinates keys

### ISSUE THREAD

**Issue by jeremysze** [ywnch/toolbox#2]
Can you explain why/how the counts of `nodes_meter` and `nodes_id_dict` differ in your report issues segment of your code? 

Thank you!

**Comment by ywnch** [comment]
From what I can recall, I think there was a case that my data consists of POIs with different keys (e.g., osmid) but potentially with exactly the same coordinates, so I include the segment to track this. One example case may be different shops in the same mall registered under the mall's coordinates. In other words, if all entities/POIs have unique coordinates, the counts should be the same. Depending on your case, having duplication may or may not be something that you want to look into.

Let me know if this does not answer your question!

**Comment by jeremysze** [comment]
Thanks! I think understanding why you included that check helps greatly! I will have to check why I find some inconsistencies because I expected my entities/POIs to be unique.
