### ISSUE TITLE
install won't work

### ISSUE THREAD

**Issue by 168-B** [ywnch/toolbox#3]
I  tried a lot of commands installing your toolbox package on my Google Colab. It did NOT WORK.
I already set up a spatial environment successfully on Colab. NX and OSMNX normally work but toolbox. Any suggestion on the issue?  

![image](https://user-images.githubusercontent.com/55384629/75097427-41e6ce80-55dd-11ea-85f8-06d4fe395c65.png)

**Comment by ywnch** [comment]
Hi, thanks for raising the issue.

This is not a packaged module on PyPI, so you won't be able to `pip install` it. Simply copy the python script (`toolbox.py`) to your notebook working directory and just import it locally in your notebook should work. Thanks!

**Comment by 168-B** [comment]
Thanks for your suggestion. I hope that your work will be very helpful. Your idea of interpolating POI to LINE instead of NODE makes sense when implementing in real-world urban scenario. So, how do I cite your work on my thesis?

**Comment by ywnch** [comment]
Hi, I am glad you find it useful. I am not sure if there is an agreed format of citing a GitHub repo, but maybe you can follow some suggestions in [this post](https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository). Or maybe create a section for all the data and source codes for reference.
