### ISSUE TITLE
Compatibility issue with updates in pandas and crs for `update_nodes`

### ISSUE THREAD

**Issue by andresrmt** [ywnch/toolbox#4]
Seems like the `inplace` parameter is now deprecated in Pandas, hence 
```python
new_nodes['osmid'].astype(str, inplace=True)
```
in line `110` would change to
```python
new_nodes['osmid'] = new_nodes['osmid'].astype(str, copy=False)
```
Similarly, the `crs` dictionary keyword in lines `99` and `100`
```python
new_nodes = gpd.GeoDataFrame(new_points, columns=['geometry'],
                                         crs={'init': 'epsg:3857'})
```
now produces the following warning:
```python
/opt/anaconda3/lib/python3.7/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
```
The following fix goes through:
```python
new_nodes     = gpd.GeoDataFrame(new_points, columns=['geometry'])
new_nodes.crs = 'epsg:3857'
new_nodes     = new_nodes.to_crs('epsg:3857')
```

Is there any reason to use `EPSG:3857`, and could it be a keyword in the function statement? According to [Spatial reference](https://spatialreference.org/ref/sr-org/6864/), its usage seems to explain why the new length of segments will not equal exactly to the length of the original edge.

**Comment by ywnch** [comment]
Hi, thanks for the feedback, `astype` and `crs` now fixed, also included a kwarg for `meter_epsg` and fix other issues related to dependency updates (now recorded in `requirements.txt`). As to which EPSG to use, I am not aware of this either, but I guess we may refer to this discussion: https://gis.stackexchange.com/questions/259121/transformation-functions-for-epsg3395-projection-vs-epsg3857
